#!/usr/bin/python
# -*- coding: utf-8 -*-
import os


# set the settings file's path to environment
os.environ['SETTINGS_PATH'] = 'server.config.settings'
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

os.path.join(BASE_DIR)

if __name__ == '__main__':
    from ../../server import src
    src.start()


