# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='session',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
