# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=128)),
                ('expire', models.IntegerField(default=300, verbose_name='超时时间(s)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Account')),
                ('host_user_bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.BindHostUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('host_user_bind', 'val')]),
        ),
    ]
