# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20171025_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='val',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([]),
        ),
    ]
