# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20171026_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeout',
            field=models.IntegerField(default=300, verbose_name='任务超时'),
        ),
    ]
