# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20171209_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.UserGroup', verbose_name='用户组'),
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ur',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ur',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Role', verbose_name='角色'),
        ),
    ]
