# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20171219_0812'),
        ('app01', '0002_userinfo_user_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='部门名称')),
                ('description', models.TextField(verbose_name='部门情况描述')),
                ('floor', models.IntegerField(verbose_name='部门所在楼层')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.SmallIntegerField(choices=[(0, '新建项目'), (1, '维护'), (2, '改造')], default=0)),
                ('status_type', models.SmallIntegerField(choices=[(0, '未完成'), (1, '完成'), (2, '在建')], default=0)),
                ('duration', models.IntegerField(verbose_name='工期')),
                ('price', models.FloatField(default=0, verbose_name='费用')),
                ('start_data', models.DateField(verbose_name='项目开始日期')),
                ('end_data', models.DateField(blank=True, null=True, verbose_name='项目结束日期')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(help_text='添加项目进行到第几天', verbose_name='节次')),
                ('date', models.DateField(auto_now_add=True, verbose_name='开始工程日期')),
                ('project_detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='项目/报修人电话号码', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='项目/报修人')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=32)),
                ('notes', models.TextField(verbose_name='项目/报修者联系记录')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ReporterFollowerUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='跟进内容')),
                ('status', models.IntegerField(choices=[(1, '项目/维护未完成'), (2, '项目/维护1周完成'), (3, '项目/维护2周完成'), (4, '项目/维护1个月完成'), (5, '项目/维护2个月完成'), (6, '项目/维护3个月完成'), (7, '项目/维护3个月以上完成')], help_text='项目/维修此时的状态')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('memo', models.TextField(blank=True, default=None, null=True, verbose_name='备注')),
                ('data_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rbac.User')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.WorkSpace', verbose_name='所属办公区'),
        ),
        migrations.AddField(
            model_name='reporterfollowerup',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserProfile', verbose_name='跟踪人'),
        ),
        migrations.AddField(
            model_name='reporterfollowerup',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Reporter', verbose_name='项目/报修者'),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserProfile', verbose_name='项目工程师'),
        ),
        migrations.AddField(
            model_name='projectrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ProjectList', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='staff',
            field=models.ManyToManyField(to='app01.UserProfile', verbose_name='负责人员'),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='work_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.WorkSpace', verbose_name='办公区'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrecord',
            unique_together=set([('project', 'day_num')]),
        ),
    ]
