# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171031_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='m2m',
            field=models.ManyToManyField(blank=True, null=True, to='app01.Role'),
        ),
    ]
